# -*- coding: utf-8 -*-
"""Pipeline_working.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySSDOHfE996J7OLg4D7djW9g-8ZGcKPU
"""

!pip install -q "transformers==4.41.2" "trl==0.9.6" "peft==0.11.1" "accelerate==0.31.0" "bitsandbytes==0.43.1" "datasets==2.19.0" -U bitsandbytes triton 2>/dev/null

import os, shutil
os.makedirs("data", exist_ok=True)
shutil.move("financial_qa.json", "data/financial_qa.json")

!ls data/

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q --force-reinstall numpy==1.26.4

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q -U bitsandbytes triton

from pipeline import finetune_with_qlora
finetune_with_qlora()

